---
- hosts: db
  become: yes
  tasks:
    - yum:
        name: httpd
        state: latest
    - lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080
    - service:
        name: httpd
        state: restarted
    - command: chkconfig httpd on
    - file:
        path: /var/www/html
        owner: ansible
        group: ansible
        mode: '0775'
    - command: echo "<html><h1>welcome to cloud guru</h1></html>" > index.html
